name: Daily Scraper Job

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run Scraper
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ELASTICSEARCH_URL: ${{ secrets.ELASTIC_URL }}
        run: |
          docker build --no-cache -t aggregator-scraper -f EventAggregator.Collector/Dockerfile .
          docker run --rm \
            -e Gemini__ApiKey=$GEMINI_API_KEY \
            -e Elasticsearch__Url=$ELASTICSEARCH_URL \
            aggregator-scraper
